#!/bin/bash
#
# Name: hooks/post-update
# Desc: Git post-update hook
#
# This script generates syslog messages for each non-merge commit that it
# receives. The idea is to be able to quickly correlate git commits to the
# Puppet repository with Puppet breakage.
#
# Copyright (C)2013 Will (Wil) Cooley
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#


GIT_DIR=$(git rev-parse --git-dir)

desc=$(head -n1 $GIT_DIR/description)

# Redirect stdout & stderr using process substitution to 'logger'
exec > >(logger -t "git-post-update" -i -p user.info)
exec 2> >(logger -t "git-post-update" -i -p user.err)

for ref in "$@"; do
    git log -1 --no-merges \
        --format="git_repo=\"$desc\" git_commit=\"%h\" git_author=\"%ae\" git_subject=\"%s\"" \
        "$ref"
done
